# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a0182d2a5af9ca73dccb10651fd52bdb"
name = "Snapquote"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_customers,write_customers,read_companies,write_companies,read_draft_orders,write_draft_orders,read_orders,write_orders"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
automatically_update_urls_on_dev = true
